export const process = {
  env: {
    VUE_APP_FIREBASE_API_KEY: 'AIzaSyDWTWq3MP25YiqY0dPOpJjoB6r1rkmlmQs',
    VUE_APP_FIREBASE_AUTH_DOMAIN: 'tech-role.firebaseapp.com',
    VUE_APP_FIREBASE_DATABASE_URL: 'https://tech-role.firebaseio.com',
    VUE_APP_FIREBASE_PROJECT_ID: 'tech-role',
    VUE_APP_FIREBASE_STORAGE_BUCKET: 'tech-role.appspot.com',
    VUE_APP_FIREBASE_MESSAGING_SENDER_ID: '81646843326',
    VUE_APP_FIREBASE_APP_ID: '1:81646843326:web:098f3a782c7813831135ef',
    VUE_APP_FIREBASE_MEASUREMENT_ID: 'G-MF26K60YW1'
  }
}
